config/routes.rb
Instaslide::Application.routes.draw do
  devise_for :users

  get "home/index"

  resources :slides

  resources :whiteboards

  root :to => "home#index"
  
  match "whiteboards/convert_image_task", :to => "whiteboards#convert_image_task", :as => "task"

  # See how all your routes lay out with "rake routes"

end

app/models/slide.rb
class Slide < ActiveRecord::Base
  # Paperclip'ed doc, back from Turk
  has_attached_file :doc

  before_save :clean_filename
  
  belongs_to :user
  
  	# Devise
	def self.visible_by(user)
	  if user.is_admin
		Slide.all
	  else
	    Slide.where :user_id => user.id
	  end
	end


  
  
  def clean_filename
     doc_file_name.gsub!(' ', '_')
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :stripe_customer_id
  
  
  has_many :slides
  has_many :whiteboards

  def self.check_existence_or_make_user_with_email(email)
		user = User.find_by_email(email)
		if user
			return user
		else
			new_user = User.new
			random_password = User.generate_random_password
			new_user.email = email
			new_user.password = random_password
			new_user.password_confirmation = random_password
			new_user.save
			new_user.reload
			#new_user.send_welcome_email_signup
			return new_user
		end
	end

	def self.generate_random_password
		#generate a random string consisting of strings and digits
		chars = ("a".."z").to_a + ("A".."Z").to_a + ("0".."9").to_a
		newpass = ""
		1.upto(10) { |i| newpass << chars[rand(chars.size-1)] }
		return newpass
	end

	def self.has_payment_info?
		!!self.stripe_customer_id?
	end
  
end

app/models/whiteboard.rb
class Whiteboard < ActiveRecord::Base
  # Paperclip'd image, into Turk
  has_attached_file :pic
  
  before_save :clean_filename
  
  belongs_to :user

  	# Devise
	def self.visible_by(user)
	  if user.is_admin
		Whiteboard.all
	  else
	    Whiteboard.where :user_id => user.id
	  end
	end

  
  def clean_filename
     pic_file_name.gsub!(' ', '_')
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

	def new
		@title = 'Sign Up For Instaslide'
	end

	def create
	end

	def destroy
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/slides_controller.rb
class SlidesController < ApplicationController

  def receive 
  end
  
  def approve #and reject
	hits = RTurk::Hit.all_reviewable

	puts "#{hits.size} reviewable hits. \n"

	unless hits.empty?
	  puts "Reviewing all assignments"

  # Need to edit this part to do rejections too
	  hits.each do |hit|
	    hit.assignments.each do |assignment|
		puts assignment.answers['tags']
		assignment.approve! if assignment.status == 'Submitted'
	    end
	  end
	end
  end
  
  
  def clear_hits
  
	hits = RTurk::Hit.all_reviewable

	puts "#{hits.size} reviewable hits. \n"

	unless hits.empty?
	  puts "Approving all assignments and disposing of each hit!"

	  hits.each do |hit|
	    hit.expire!
	    hit.assignments.each do |assignment|
		assignment.approve!
	    end
	    hit.dispose!
	  end
	end

  
  end
  
  
  def apply_rating
  end


  # GET /slides
  # GET /slides.xml
  def index
    @slides = Slide.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @slides }
    end
  end

  # GET /slides/1
  # GET /slides/1.xml
  def show
    @slide = Slide.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @slide }
    end
  end

  # GET /slides/new
  # GET /slides/new.xml
  def new
    @slide = Slide.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @slide }
    end
  end

  # GET /slides/1/edit
  def edit
    @slide = Slide.find(params[:id])
  end

  # POST /slides
  # POST /slides.xml
  def create
    @slide = Slide.new(params[:slide])

    respond_to do |format|
      if @slide.save
        format.html { redirect_to(@slide, :notice => 'Slide was successfully created.') }
        format.xml  { render :xml => @slide, :status => :created, :location => @slide }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @slide.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /slides/1
  # PUT /slides/1.xml
  def update
    @slide = Slide.find(params[:id])

    respond_to do |format|
      if @slide.update_attributes(params[:slide])
        format.html { redirect_to(@slide, :notice => 'Slide was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @slide.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /slides/1
  # DELETE /slides/1.xml
  def destroy
    @slide = Slide.find(params[:id])
    @slide.destroy

    respond_to do |format|
      format.html { redirect_to(slides_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/whiteboards_controller.rb
class WhiteboardsController < ApplicationController

  def convert_image_task
  # just to pull up the view
  end

  # Use Paperclip to attach a file
  def upload
  end
  
  # Send file to Turk
  # need to pass the current image to this guy as a parameter?
  def submit
    RTurk.setup(AKIAJETT5WWWOMFUITCQ, h6khH304Eb/VEqs4DujJ6VfsI0kzYuUsnCXw7U+0, :sandbox => true)
    hit = RTurk::Hit.create(:title => "Create a powerpoint slide based on a picture") do |hit|

    hit.description = 'Given an image of a whiteboard diagram, extract images and diagram elements and create a quick powerpoint slide.'
# 	not sure if this is a real thing
    hit.keywords = 'image, slide, powerpoint, whiteboard, text, diagram'

    hit.question(task_path,
                 :frame_height => 1000)  # pixels for iframe
    hit.reward = 0.25
    hit.assignments = 1
    hit.qualifications.add :approval_rate, { :gt => 90 }
    end
  end


  # GET /whiteboards
  # GET /whiteboards.xml
  def index
    @whiteboards = Whiteboard.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @whiteboards }
    end
  end

  # GET /whiteboards/1
  # GET /whiteboards/1.xml
  def show
    @whiteboard = Whiteboard.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @whiteboard }
    end
  end

  # GET /whiteboards/new
  # GET /whiteboards/new.xml
  def new
    @whiteboard = Whiteboard.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @whiteboard }
    end
  end

  # GET /whiteboards/1/edit
  def edit
    @whiteboard = Whiteboard.find(params[:id])
  end

  # POST /whiteboards
  # POST /whiteboards.xml
  def create
    @whiteboard = Whiteboard.new(params[:whiteboard])

    respond_to do |format|
      if @whiteboard.save
        format.html { redirect_to(@whiteboard, :notice => 'Whiteboard was successfully created.') }
        format.xml  { render :xml => @whiteboard, :status => :created, :location => @whiteboard }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @whiteboard.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /whiteboards/1
  # PUT /whiteboards/1.xml
  def update
    @whiteboard = Whiteboard.find(params[:id])

    respond_to do |format|
      if @whiteboard.update_attributes(params[:whiteboard])
        format.html { redirect_to(@whiteboard, :notice => 'Whiteboard was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @whiteboard.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /whiteboards/1
  # DELETE /whiteboards/1.xml
  def destroy
    @whiteboard = Whiteboard.find(params[:id])
    @whiteboard.destroy

    respond_to do |format|
      format.html { redirect_to(whiteboards_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/helpers/whiteboards_helper.rb
module WhiteboardsHelper
end

app/views/home/index.html.erb
<h1>Instaslide</h1>
</br>
<h2>Have you ever wished that you could just focus on the ideas rather than writing slides?</h2>
</br>
<h3>Upload a picture of a recent whiteboard and witness the magic</h3>
</br>

<%= link_to 'Slides', slides_path  %> | 
<%= link_to 'Whiteboards', whiteboards_path  %>
</br>
<%= link_to 'Home', root_path  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Instaslide</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/slides/_form.html.erb
<%= form_for(@slide) do |f| %>
  <% if @slide.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@slide.errors.count, "error") %> prohibited this slide from being saved:</h2>

      <ul>
      <% @slide.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/slides/edit.html.erb
<h1>Editing slide</h1>

<%= render 'form' %>
<% form_for :slide, @slide, :url => slides_path, :html => { :multipart => true } do |form| %>
  <%= form.file_field :doc %>
<% end %>

<%= link_to 'Show', @slide %> |
<%= link_to 'Back', slides_path %>

app/views/slides/index.html.erb
<h1>Listing slides</h1>

<table>
  <tr>
	<th>ID</th>
    <th>File Name</th>
	<th>URL</th>
  
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @slides.each do |s| %>
  <tr>
    <td><%= s.id %></td>
	<td><%= s.pic_file_name %></td>
	<td><%= s.name %></td>
  
    <td><%= link_to 'Show', s %></td>
    <td><%= link_to 'Edit', edit_slide_path(s) %></td>
    <td><%= link_to 'Destroy', s, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Slide', new_slide_path %>
</br>
<%= link_to 'Slides', slides_path  %>
<%= link_to 'Whiteboards', whiteboards_path  %>
<%= link_to 'Home', root_path  %>

app/views/slides/new.html.erb
<h1>New slide</h1>

<%= render 'form' %>
<% form_for :slide, @slide, :url => slides_path, :html => { :multipart => true } do |form| %>
  <%= form.file_field :doc %>
<% end %>
<%= link_to 'Back', slides_path %>

app/views/slides/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_slide_path(@slide) %> |
<%= link_to 'Back', slides_path %>

app/views/whiteboards/_form.html.erb
<%= form_for(@whiteboard) do |f| %>
  <% if @whiteboard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@whiteboard.errors.count, "error") %> prohibited this whiteboard from being saved:</h2>

      <ul>
      <% @whiteboard.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/whiteboards/edit.html.erb
<h1>Editing whiteboard</h1>

<%= render 'form' %>
<% form_for :whiteboard, @whiteboard, :url => whiteboards_path, :html => { :multipart => true } do |form| %>
  <%= form.file_field :pic %>
<% end %>
<%= link_to 'Show', @whiteboard %> |
<%= link_to 'Back', whiteboards_path %>

app/views/whiteboards/index.html.erb
<h1>Listing whiteboards</h1>

<table>
  <tr>
	<th>ID</th>
    <th>File Name</th>
	<th>URL</th>
  
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @whiteboards.each do |w| %>
  <tr>
    <td><%= w.id %></td>
	<td><%= w.pic_file_name %></td>
	<td><%= w.name %></td>
    <td><%= link_to 'Show', w %></td>
    <td><%= link_to 'Edit', edit_whiteboard_path(w) %></td>
    <td><%= link_to 'Destroy', w, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Whiteboard', new_whiteboard_path %>
</br>

<%= link_to 'Slides', slides_path  %> | 
<%= link_to 'Whiteboards', whiteboards_path  %>
</br>
<%= link_to 'Home', root_path  %>

app/views/whiteboards/new.html.erb
<h1>New whiteboard</h1>

<%= render 'form' %>
<% form_for :whiteboard, @whiteboard, :url => whiteboards_path, :html => { :multipart => true } do |form| %>
  <%= form.file_field :pic %>
<% end %>

<%= link_to 'Back', whiteboards_path %>

app/views/whiteboards/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_whiteboard_path(@whiteboard) %> |
<%= link_to 'Back', whiteboards_path %>